language: python

matrix:
  include:
    - python: 3.7
      env: TOX_ENV=py37-django22
    - python: 3.7
      env: TOX_ENV=py37-django30
    - python: 3.7
      env: TOX_ENV=py37-django31
    - python: 3.7
      env: TOX_ENV=py37-django32
    - python: 3.8
      env: TOX_ENV=py38-django22
    - python: 3.8
      env: TOX_ENV=py38-django30
    - python: 3.8
      env: TOX_ENV=py38-django31
    - python: 3.8
      env: TOX_ENV=py38-django32
    - python: 3.9
      env: TOX_ENV=py39-django22
    - python: 3.9
      env: TOX_ENV=py39-django30
    - python: 3.9
      env: TOX_ENV=py39-django31
    - python: 3.9
      env: TOX_ENV=py39-django32
    - python: 3.9
      env: TOX_ENV=py39-djangostable
    - env: TOX_ENV=flake8

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
